name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: yarn install

    - name: Build the React app
      run: yarn build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build --no-cache -t sx0527/my-react-app:latest .
        docker push sx0527/my-react-app:latest

    - name: SSH and deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull sx0527/my-react-app:latest
          docker stop react-container
          docker rm react-container
          docker run -d -p 3000:3000 --name react-container sx0527/my-react-app:latest
          sleep 10  # 컨테이너가 시작될 시간을 주기 위해 약간의 지연을 추가
          docker logs react-container  # 컨테이너 로그를 확인